### PR TITLE
update icon

### PR DESCRIPTION
**Pull request by zeref-dragneel**

### CODE REVIEW

**Comment by cbotsikas** [comment]
Hi @zeref-dragneel 
Thanks for the PR. I'm missing some context here. Why did you do the pull request? What's the license of the image? Is there a source available?

**Comment by zeref-dragneel** [comment]
> Hi @zeref-dragneel Thanks for the PR. I'm missing some context here. Why did you do the pull request? What's the license of the image? Is there a source available?

Well, I've actually been thinking about this since I installed facebook adblock, I like the facebook icon
image, so I think change the character would be enough. rough example, i'm not the best at using photoshop, just a suggestion...

image

**Comment by cbotsikas** [comment]
I'm trying to understand why the marked gaps 1, 2 and 3 are different in size. I think this is kind of odd design.

Screenshot 2022-04-14 at 09 49 33

**Comment by cbotsikas** [comment]
In fact it's so odd, that I was able to find two logos with exactly the same design from 2015 and 2016..
image

**Comment by tiratatp** [comment]
> I'm trying to understand why the marked gaps 1, 2 and 3 are different in size. I think this is kind of odd design.
> 
> Screenshot 2022-04-14 at 09 49 33

When you zoom in you can see the red pixels as well.

Let's not use a logo if we don't know what type of copyright it has.

**Pull request closed without merging**
