### PR TITLE
bump to 1.9.3

### PR DESCRIPTION
**Pull request by cbotsikas**

### CODE REVIEW

**Comment by cbotsikas** [comment]
here's the bump changes if you want to tag and start the deployment

**Comment by tiratatp** [comment]
It's just the Swedish language right? Could you upgrade outdated dependencies too? 

Just FYI. This might take a month or more for Chrome so we don't want to bump unless the feature is important. And while the extension is being review, we won't be able to publish a new version for Chrome.

**Comment by tiratatp** [comment]
IMO we should wait until there is a bit more important feature/fix before publish a new version.

**Comment by tiratatp** [comment]
Closed this since we already bumped to 1.9.3

**Pull request closed without merging**
