### PR TITLE
bump to 1.8.3

### PR DESCRIPTION
**Pull request by cbotsikas**

### CODE REVIEW

**Comment by cbotsikas** [comment]
well, the publishing executed and looks ok, at least for the firefox plugin which is already public, but I should have either waited for this PR to be squashed/merged into master or directly push the commit to the master (if I have write permissions) before I push the new tag. 
Now, I've created the new branch, committed the bump and created the new version tag. Once I pushed the branch, including the tags, the deploy process started and thankfully, on the correct branch (not the master).
How did you do it last time @tiratatp ? Did you commit to the master directly and then pushed the tags?

**Comment by tiratatp** [comment]
I didn't create a PR last time. I tag and push to master directly.

I think it works but we do not want the workflow to run if the tag is still in PR. I'll fix.

**Comment by tiratatp** [comment]
@cbotsikas I'm a bit confused. Did the workflow run if the tag is still in PR? We don't want that right?

Imagine someone can just come in, write malicious code, and create a PR with a tag?

Oh wait. Can the tag be a part of PR?

**Comment by cbotsikas** [comment]
No, tags are not part of a PR. Tags can only be created here, on this fork. I tried creating the tag on my fork, but there's not way to PR that. That's why I created the branch and the tag here. 

When I pushed here and then created the PR, the deploy workflow had already run and was finished. So it was triggered by the time I pushed the branch with the tags `git push --tags origin bump-1.8.3`. The tags can be created and pushed, without any commits. I was able to create a tag, because I have access to create branches and tags. I don't know if you gave me access for master too, since i have no access to the settings. If I have write access on master, maybe it would be better to create the bump commit directly on master and then create an push the new tag.

I don't see how someone else, without permission, could create new tags here. 

For the workflow, I think that the tags should be created and pushed on github, just after the bump commit has landed in master branch. I guess this should be a task to however approves and merges the last commit that would require a new release. What do you think? Since you're the owner you should decide that. If you need help on that, It's ok by me, but maybe we should have the process described and written. 
I think the only limitation in the workflow is the required review for the PRs. 
Do you want to bump the version within a feature/bug/whatever PR, dedicate PR (like I did today) or directly on master?

**Comment by cbotsikas** [comment]
Can you also check the Chrome store? I still see v1.8.2. Firefox store has already the v1.8.3.

**Pull request merged**
